(in-package shi)

(defun deque-tests ()
  (let ((q (new-deque 1 2)))
    (assert (= (deque-length q) 2))
    (push-back q 3)
    (assert (= (deque-length q) 3))
    (assert (= (pop-back q) 3))
    (dotimes (i 2)
      (assert (= (pop-front q) (1+ i))))
    (assert (zerop (deque-length q)))))

(defun stack-tests ()
  (let* ((s (new-stack))
	 (v1 (new-cell t-int 1))
	 (v2 (new-cell t-int 2)))
    (push-cell s v1)
    (push-cell s v2)
    (assert (= 2 (stack-length s)))
    (assert (cell= v2 (peek-cell s)))
    (assert (cell= v2 (pop-cell s)))
    (assert (cell= v1 (peek-cell s)))
    (assert (cell= v1 (pop-cell s)))
    (assert (null (peek-cell s)))))

(defun tests ()
  (deque-tests)
  (stack-tests)
  (vm-tests))
